// @generated
// This file is @generated by prost-build.
/// One message per block, emitted even when none of the watched pools traded,
/// so a consumer can tell a quiet market from a dead stream. Every message
/// carries the block time, so a price can be placed against a deadline rather
/// than against the moment it happened to arrive.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BlockPrices {
    #[prost(uint64, tag="1")]
    pub block_number: u64,
    #[prost(string, tag="2")]
    pub block_hash: ::prost::alloc::string::String,
    #[prost(uint64, tag="3")]
    pub timestamp_ms: u64,
    /// Only the pools that traded in this block, sorted by address.
    #[prost(message, repeated, tag="4")]
    pub prices: ::prost::alloc::vec::Vec<PoolPrice>,
}
/// Decodes any message while reading none of it. The module takes the raw
/// block as an input only so that it runs on every block (see src/lib.rs), and
/// has no use for anything inside it.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Ignored {
}
/// A pool's state at the end of the block, after its last swap.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PoolPrice {
    /// 0x-prefixed lowercase address
    #[prost(string, tag="1")]
    pub pool: ::prost::alloc::string::String,
    /// decimal-adjusted, in the orientation the params asked for
    #[prost(double, tag="2")]
    pub price: f64,
    /// the exact price, for anyone re-deriving it
    #[prost(string, tag="3")]
    pub sqrt_price_x96: ::prost::alloc::string::String,
    /// in-range liquidity after the swap; a depth weight
    #[prost(string, tag="4")]
    pub liquidity: ::prost::alloc::string::String,
    /// swaps in this pool in this block
    #[prost(uint32, tag="5")]
    pub swaps: u32,
    /// ordinal of the last swap; orders swaps inside the block
    #[prost(uint64, tag="6")]
    pub ordinal: u64,
    /// transaction of the last swap, for settlement receipts
    #[prost(string, tag="7")]
    pub tx_hash: ::prost::alloc::string::String,
}
// @@protoc_insertion_point(module)
